server:
  port: 80

logging:
  level:
    com: debug

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.example
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

spring:
  profiles:
    active: druid
  devtools:
    restart:
      enabled: true